# Generated by Django 3.1.7 on 2021-04-03 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='faq',
            new_name='questions',
        ),
    ]
